name: dice_roller
description: Simulate standard and custom dice rolls in Dart/Flutter.
license: MIT
version: 0.0.1
homepage: https://github.com/tsnash/dice-roller
issue_tracker: https://github.com/tsnash/dice-roller/issues
publish_to: 'none' # Prevent accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  test:
  flutter_lints: ^6.0.0
