name: dice_roller
description: Simulate standard and custom dice rolls in Dart/Flutter.
version: 0.0.2
repository: https://github.com/tsnash/dice-roller
issue_tracker: https://github.com/tsnash/dice-roller/issues
homepage: https://github.com/tsnash/dice-roller
documentation: https://github.com/tsnash/dice-roller
topics: [dice, random, rng]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  test:
  lints: ^6.0.0
